In [ ]:
import numpy as np

X = np.array(([5, 10, 3], [2, 8, 6], [1, 4, 9]), dtype=float)
y = np.array(([83, 72], [67, 86], [92, 87]), dtype=float)
X = X/np.amax(X,axis=0) 
y = y/100

def sigmoid (x):
    return 1/(1 + np.exp(-x))

def derivatives_sigmoid(x):
    return x * (1 - x)

epoch=10
lr=0.1

inputlayer_neurons = 3
hiddenlayer_neurons = 5
output_neurons = 2

wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))


for i in range(epoch):
    #Forward Propogation
    hinp1=np.dot(X,wh)
    hinp=hinp1 + bh
    hlayer_act = sigmoid(hinp)
    outinp1=np.dot(hlayer_act,wout)
    outinp= outinp1+bout
    output = sigmoid(outinp)
    
    #Backpropagation
    EO = y-output
    outgrad = derivatives_sigmoid(output)
    d_output = EO * outgrad
    EH = d_output.dot(wout.T)
    hiddengrad = derivatives_sigmoid(hlayer_act)
    d_hiddenlayer = EH * hiddengrad
    
    wout += hlayer_act.T.dot(d_output) *lr   
    wh += X.T.dot(d_hiddenlayer) *lr
    
    print ("-----------Epoch-", i+1, "Starts----------")
    print("Input: \n" + str(X)) 
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" ,output)
    print ("-----------Epoch-", i+1, "Ends----------\n")
        
print("Input: \n" + str(X)) 
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)


-----------Epoch- 1 Starts----------
Input: 
[[1.         1.         0.33333333]
 [0.4        0.8        0.66666667]
 [0.2        0.4        1.        ]]
Actual Output: 
[[0.83 0.72]
 [0.67 0.86]
 [0.92 0.87]]
Predicted Output: 
 [[0.90618656 0.97861208]
 [0.89631867 0.97465625]
 [0.88893405 0.97135833]]
-----------Epoch- 1 Ends----------

-----------Epoch- 2 Starts----------
Input: 
[[1.         1.         0.33333333]
 [0.4        0.8        0.66666667]
 [0.2        0.4        1.        ]]
Actual Output: 
[[0.83 0.72]
 [0.67 0.86]
 [0.92 0.87]]
Predicted Output: 
 [[0.90545974 0.97852705]
 [0.89556308 0.97456077]
 [0.88816291 0.97125546]]
-----------Epoch- 2 Ends----------

-----------Epoch- 3 Starts----------
Input: 
[[1.         1.         0.33333333]
 [0.4        0.8        0.66666667]
 [0.2        0.4        1.        ]]
Actual Output: 
[[0.83 0.72]
 [0.67 0.86]
 [0.92 0.87]]
Predicted Output: 
 [[0.90472936 0.97844147]
 [0.89480419 0.97446469]
 [0.8873887  0.97115196]]
----------